# Generated by Django 4.1.2 on 2023-01-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='content1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='content2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='content3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='descimage',
            field=models.ImageField(default=1, upload_to='static/uploads/desc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='mainimage',
            field=models.ImageField(default=1, upload_to='static/uploads/main'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='quotes',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='thumbimage',
            field=models.ImageField(default=1, upload_to='static/uploads/thumb'),
            preserve_default=False,
        ),
    ]
