# Generated by Django 4.1.2 on 2023-01-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_content_blog_content1_remove_blog_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('tes_image', models.ImageField(upload_to='static/uploads/main')),
                ('name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('tes_msg', models.CharField(max_length=180)),
            ],
        ),
    ]
