# Generated by Django 4.1.2 on 2023-01-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content4',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='heading1',
            field=models.CharField(default=1, max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='heading2',
            field=models.CharField(default=1, max_length=180),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='quotes',
            field=models.CharField(max_length=150),
        ),
    ]
