# Generated by Django 4.1.2 on 2023-01-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_blog_content4_blog_heading1_blog_heading2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='descimagelink',
            field=models.CharField(default='{%static "/uploads/desc/" %}', max_length=280),
        ),
        migrations.AddField(
            model_name='blog',
            name='mainimagelink',
            field=models.CharField(default='{%static "/uploads/main/" %}', max_length=280),
        ),
        migrations.AddField(
            model_name='blog',
            name='thumbimagelink',
            field=models.CharField(default='{%static "uploads/thumb/" %}', max_length=280),
        ),
    ]
