# Generated by Django 4.1.2 on 2023-01-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_blog_descimagelink_blog_mainimagelink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descimagelink',
            field=models.CharField(default='uploads/desc/}', max_length=280),
        ),
        migrations.AlterField(
            model_name='blog',
            name='mainimagelink',
            field=models.CharField(default='uploads/main/', max_length=280),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbimagelink',
            field=models.CharField(default='uploads/thumb/', max_length=280),
        ),
    ]
