# Generated by Django 4.1.2 on 2023-01-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_blog_descimagelink_alter_blog_mainimagelink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descimagelink',
            field=models.CharField(default='uploads/desc/', max_length=280),
        ),
    ]
