# Generated by Django 4.1.2 on 2023-01-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='crimereport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crimedetail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='protectuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
