# Generated by Django 4.1.2 on 2023-01-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_crimereport_protectuser'),
    ]

    operations = [
        

    ]
