# Generated by Django 4.1.2 on 2023-01-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_crimereport_id_remove_protectuser_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='crimereport',
        ),
        migrations.DeleteModel(
            name='protectuser',
        ),
    ]
