# Generated by Django 4.1.2 on 2023-01-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_delete_crimereport_delete_protectuser'),
    ]

    operations = [
    ]
