# Generated by Django 4.1.2 on 2023-01-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_crimereport_protectuser'),
    ]

    operations = [
        
    ]
