# Generated by Django 4.1.2 on 2023-01-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_crimereport_protectuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportingcrime',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('reportername', models.CharField(max_length=100)),
                ('crimeloc', models.CharField(max_length=100)),
                ('crimedetail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='userprotection',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('userrname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('livingloc', models.CharField(max_length=100)),
            ],
        ),
    ]
