# Generated by Django 4.1.2 on 2023-01-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_reportingcrime_userprotection'),
    ]

    operations = [
        migrations.CreateModel(
            name='usersafety',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('usersafetyname', models.CharField(max_length=100)),
                ('usertelegramclientid', models.CharField(max_length=100)),
                ('otherstelegramclientid', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
