# Generated by Django 4.1.2 on 2023-01-26 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_reportingcrime_crimeproof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportingcrime',
            name='crimeproof',
        ),
    ]
