# Generated by Django 4.1.2 on 2023-01-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_reportingcrime_crimeproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingcrime',
            name='crimeproof',
            field=models.ImageField(default=1, upload_to='static/uploads/reportcrime'),
            preserve_default=False,
        ),
    ]
